name: deploy on anacnukr

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 접속 및 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 8082
          script: |
            cd /home/ana/Desktop/ana/ana-website-2026

            git pull origin main

            docker compose -f docker-compose.prod.yml down || true

            docker compose -f docker-compose.prod.yml up -d --build

            docker image prune -f